version: "3.9"
services:
  db:
    image: postgres:17
    container_name: appdatabase
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"